src/Entity/Casting.php
<?php

namespace App\Entity;

use App\Repository\CastingRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CastingRepository::class)
 */
class Casting
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $role;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $credit_order;

    /**
     * @ORM\ManyToOne(targetEntity=Person::class, inversedBy="casting")
     * @ORM\JoinColumn(nullable=false)
     * 
     */
    private $person;

    /**
     * @ORM\ManyToOne(targetEntity=Movie::class, inversedBy="castings")
     * 
     * @ORM\JoinColumn(nullable=false)
     */
    private $movie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getCreditOrder(): ?int
    {
        return $this->credit_order;
    }

    public function setCreditOrder(?int $credit_order): self
    {
        $this->credit_order = $credit_order;

        return $this;
    }

    public function getPerson(): ?Person
    {
        return $this->person;
    }

    public function setPerson(?Person $person): self
    {
        $this->person = $person;

        return $this;
    }

    public function getMovie(): ?Movie
    {
        return $this->movie;
    }

    public function setMovie(?Movie $movie): self
    {
        $this->movie = $movie;

        return $this;
    }
}

src/Form/CastingType.php
<?php

namespace App\Form;

use App\Entity\Casting;
use App\Entity\Person;
use App\Entity\Movie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FloatType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class CastingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('role',TextType::class, [
                'label' => 'role',
            ])
            ->add('credit_order',IntegerType::class, [
                'label' => 'rating',
                
            ])
        //     ->add('person',EntityType::class,[ 'class' => Person::class,
        //     'choice_label' => 'name',
        //    'expanded' => true,
        //    'multiple' => true,
        // 'choice_value' => 'id'
        //     ])
        //     ->add('movie',EntityType::class,[ 'class' => Movies::class,
        //     'choice_label' => 'name',
        //    'expanded' => true,
        //    'multiple' => true,
        // 'choice_value' => 'id'
        //     ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Casting::class,
        ]);
    }
}

src/Controller/Backoffice/GenreController.php
<?php



namespace App\Controller\Backoffice;

use App\Entity\Genre;
use App\Form\GenreType;
use App\Repository\GenreRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class GenreController extends AbstractController
{
    /**
     * @Route("backoffice/genres/", name="backoffice_genres_browse", methods={"GET"})
     */
    public function list(GenreRepository $genreRepository): Response
    {
        // TODO ajouter une pagination

        return $this->render('backoffice/genre/list.html.twig', [
            'genre_list' => $genreRepository->findAll(),
        ]);
    }

    /**
     * @Route("backoffice/genres/{id}", name="backoffice_genres_read", methods={"GET"}, requirements={"id": "\d+"})
     */
    public function read(Genre $genre): Response
    {
        return $this->render('backoffice/genre/read.html.twig', [
            'genre' => $genre,
        ]);
    }

    /**
     * @Route("backoffice/genres/{id}/edit", name="backoffice_genres_edit", methods={"GET", "POST"}, requirements={"id": "\d+"})
     */
    public function edit (Genre $genre, Request $request, ManagerRegistry $doctrine): Response
    {
        $form = $this->createForm(GenreType::class, $genre);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $entityManager = $doctrine->getManager();

            $this->addFlash('success', 'Genre modifié avec succès');
            $entityManager->flush();

            return $this->redirectToRoute('backoffice_genres_list');
        }

        return $this->render('backoffice/genre/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("backoffice/genres/add", name="backoffice_genres_add", methods={"GET", "POST"})
     */
    public function add (Request $request, ManagerRegistry $doctrine): Response
    {
        $genre = new Genre();
        $form = $this->createForm(GenreType::class, $genre);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $entityManager = $doctrine->getManager();

            $entityManager->persist($genre);

            $this->addFlash('success', 'Genre ajouté avec succès');
            $entityManager->flush();

            return $this->redirectToRoute('backoffice_genres_list');
        }

        return $this->render('backoffice/genre/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("backoffice/genres/{id}/delete", name="delete", methods={"GET"}, requirements={"id": "\d+"})
     */
    public function delete (Genre $genre, ManagerRegistry $doctrine): Response
    {
        // TODO penser à ajouter un tokenCSRF 

        $entityManager = $doctrine->getManager();
        $entityManager->remove($genre);
        $entityManager->flush();

        $this->addFlash('success', 'Genre supprimé avec succès');

        return $this->redirectToRoute('backoffice_genres_list');

    }




    
}

src/Controller/Backoffice/MainController.php
<?php

namespace App\Controller\Backoffice;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class MainController extends AbstractController
{
    /**
     * @Route("/backoffice/main", name="backoffice_homepage")
     * @IsGranted("ROLE_MANAGER")
     */
    public function index(): Response
    {
        return $this->render('backoffice/main/home.html.twig');
    }
}

src/Controller/Backoffice/MovieController.php
<?php

namespace App\Controller\Backoffice;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\MovieRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Genre;
use App\Entity\Movie;
use App\Form\MovieeditType;
use Symfony\Component\String\Slugger\SluggerInterface;
use App\Service\Myslugger;


class MovieController extends AbstractController
{
    /**
     * @Route("/backoffice/movie", name="backoffice_movie_list")
     */
    public function list(MovieRepository $movieRepository): Response
    {
        $movies = $movieRepository->findAll();


        return $this->render('backoffice/movie/list.html.twig', [
            'movies' => $movies
        ]);
    }


     /**
     * @Route("/backoffice/movie/{id}/read", name="backoffice_movie_read", requirements={"id"="\d+"}, methods={"GET"})
     */
    public function show(int $id, MovieRepository $movieRepository): Response
    {
       

        // $movie = ShowModel::getShow($movieId);
        $movie = $movieRepository->findOneWithAllData($id);

        

        // on vérifie si l'identifiant existe dans le tableau
        if ( is_null($movie))
        {
            
            throw $this->createNotFoundException('The show does not exist');
        }

        return $this->render('backoffice/movie/read.html.twig', [
            'movie' => $movie,
            'movie_id' => $movie->getId(),
        ]);

        
    }
    
     /**
     * @Route("/backoffice/movie/{id}/edit", name="backoffice_movie_edit", requirements={"id"="\d+"}, methods={"GET","POST"})
     */
    public function edit(int $id, MovieRepository $movieRepository,ManagerRegistry $doctrine,Request $request,SluggerInterface $slugger): Response
    {
       

      
        $movie = $movieRepository->findOneWithAllData($id);
        //$movie = new Movie();
       

        // préparation des données
       
        $form = $this->createForm(MovieeditType::class, $movie);
        
        //dd($form);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            // récupérer les données
           
            $updateDate = new \DateTime();
            $movie->setUpdatedAt($updateDate);
            // valider les données
            $movie->setSlug($slugger->slug(strtolower($movie->getTitle())));

             $entityManager = $doctrine->getManager();
             $entityManager->flush();
            
           // dd( $movie);
            // // ajouter un flash message (facultatif)
            $this->addFlash('success', 'Votre movie a bien été modifié');
            // // rediriger
             return $this->redirectToRoute('backoffice_movie_read',['id' => $movie->getId()]);
        }

        return $this->renderform('backoffice/movie/edit.html.twig', [
            'form' => $form,
            'movie' => $movie,
            
        ]);

        
    }

    /**
     * @Route("/backoffice/movie/{id}/delete", name="backoffice_movie_delete", requirements={"id"="\d+"}, methods={"GET"})
     */
    public function delete(Movie $movie, ManagerRegistry $doctrine): Response
    {
        // Un objet ParamConverter s'occupe de 
        // récupérer l'article en fonction de l'id fournit
        // si article non trouvé alors il renvoit une 404

        // si le code continue c'est que l'article a été trouvé et qu'il est dans l'objet $article

        // dire à doctrine de supprimer l'article
        $entityManager = $doctrine->getManager();
        $entityManager->remove($movie);
        
        // dire à doctrine d'exécuter la requête de suppression
        $entityManager->flush();

        // redirection
        return $this->redirectToRoute('backoffice_movie_list');
    }
    

     /**
     * displays the review
     *
     * @return Response
     * 
     * @Route("/backoffice/movie/add", name="backoffice_movie_add", methods={"GET", "POST"})
     */
    public function add(Request $request,MovieRepository $movieRepository,ManagerRegistry $doctrine,Myslugger $slugger) :Response
    {
        // préparation des données
        $movie = new Movie();
        $form = $this->createForm(MovieeditType::class, $movie);
       
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) { 
            $created = new \DateTime();
            $movie->setCreatedAt($created);
            $movie->setSlug($slugger->slugify($movie->getTitle()));
               
                $entityManager = $doctrine->getManager();  
               $entityManager->persist($movie);
           
               // dire à doctrine d'exécuter les requêtes
              $entityManager->flush();
            
   
           
             return $this->redirectToRoute('backoffice_movie_list');
        }

        return $this->render('backoffice/movie/add.html.twig',[
             'form' => $form->createView(),
        ]);
    }








}

src/Controller/Backoffice/UserController.php
<?php

namespace App\Controller\Backoffice;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\PasswordHasher\PasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/backoffice/users")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="backoffice_user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('backoffice/user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="backoffice_user_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $hasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);


            $hashedPassword = $hasher->hashPassword($user, $user->getPassword());
            $user->setPassword($hashedPassword);
            
            $entityManager->flush();

            return $this->redirectToRoute('backoffice_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('backoffice/user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="backoffice_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('backoffice/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="backoffice_user_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('backoffice_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('backoffice/user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="backoffice_user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('backoffice_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/backoffice/casting/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <h1>Ajouter un Casting</h1>

    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    
    {{ form_row(form.role) }}
    {{ form_row(form.credit_order) }}
   
  <button class="btn btn-success " >Add</button>
    {{ form_end(form) }}
   
     {# {{ form_row(form.movieName,{'attr': {'placeholder': movie.title}}) }}   #}
    
   
</div>
{% endblock %}


{% block title %}
Add a casting
{% endblock %}

templates/backoffice/casting/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <h1>Ajouter un Casting</h1>

    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    
    {{ form_row(form.role) }}
    {{ form_row(form.credit_order) }}
   
  <button class="btn btn-success " >Add</button>
    {{ form_end(form) }}
   
     {# {{ form_row(form.movieName,{'attr': {'placeholder': movie.title}}) }}   #}
    
   
</div>
{% endblock %}


{% block title %}
Add a casting
{% endblock %}

templates/backoffice/casting/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MovieController!{% endblock %}

{% block body %}
  <div class="container my-4">
        <a href="{{path('backoffice_casting_add')}}" class="btn btn-success float-end">Ajouter</a>
        <h2>Liste des Castings</h2>
        <table class="table table-hover mt-4">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">role</th>
                    <th scope="col">credit-order</th>
                   
                     <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
              {% for casting in castings %}  
                <tr>
                    <th scope="row">{{casting.id}}</th>
                    <td>{{casting.role}}</td>
                    <td>{{casting.creditOrder}}</td>
                    
                    <td class="text-end">
                        <a href="{{path('backoffice_casting_read',{id:casting.id})}}" class="btn btn-sm btn-warning">
                            <i class="fa fa-pencil-square-o" aria-hidden="true">Detail</i>
                        </a>
                        <a href="{{path('backoffice_casting_edit',{id:casting.id})}}" class="btn btn-sm btn-warning">
                            <i class="fa fa-pencil-square-o" aria-hidden="true">Update</i>
                        </a>
                         <a href="{{path('backoffice_casting_delete',{id:casting.id})}}" class="btn btn-sm btn-danger">
                            <i class="fa fa-pencil-square-o" aria-hidden="true">delete</i>
                        </a>
                        <!-- Example single danger button -->
                       
                        {# <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-danger dropdown-toggle"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Oui, je veux supprimer</a>
                                <a class="dropdown-item" href="#" data-toggle="dropdown">Oups !</a>
                            </div>
                        </div> #}
                    </td>
                </tr>
               {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/backoffice/casting/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail du film{% endblock %}

{% block body %}

<div class="container bg-lighttt pt-5">

                 <div class="d-flex justify-content-around mb-4" >
                
                        <a href="{{path('backoffice_movie_list')}}" class="btn btn-success float-end">Retour</a>
                        <a  class="btn btn-success float-end" href="{{path('backoffice_movie_edit',{id : casting.id})}}">Modify</a>
                   
                </div>

    <div class="row mb-2">

        <div class="col">
            <div
                class="row g-0 border rounded overflow-hidden flex-md-row align-items-start mb-4 shadow-smmm position-relative">
                

                <div class="col-8 p-4 d-flex flex-column position-static bg-light">
                   
                   

                   

                    <dl class="row">
                        <dt class="col-sm-12">Casting Details</dt>
                        <dd class="col-sm-12">

                         {% for persons in casting.person %}
                      
                            Acteur: {{ persons.firstName }} role: {{ persons.role }}<br>
    
                             {% endfor %} 
                             
                             Movies :
                                {% for movies in casting.movie %}
                                    {{ movies.title }}, 
                                {% endfor %}
                        </dd>
                        
                    </dl>

                  

                </div>
                
            </div>

        </div>

    </div>
   

</div>
{% endblock %}